### ISSUE TITLE
Nospam value is inserted into the ID reversed

### ISSUE THREAD

**Issue by pranomostro** [pranomostro/ratox#19]
Steps to reproduce:

```
$ cat id
5071B5559DA51AC81958755671617BDD2A968E320C73A536E9E185426F7F2319215D89AF812D
$ echo AABBCCDD >nospam/in
$ cat id
5071B5559DA51AC81958755671617BDD2A968E320C73A536E9E185426F7F2319DDCCBBAA4FB9
```

Expected result:

```
5071B5559DA51AC81958755671617BDD2A968E320C73A536E9E185426F7F2319AABBCCDD4FB9
```

**Comment by pranomostro** [comment]
See https://github.com/TokTok/c-toxcore/issues/205.

**Comment by z3bra** [comment]
This part is fixed within ratox (compiled against irungentoo/toxcore). Toktok seems to provide a "fix". Not sure what it's worth.

**Comment by pranomostro** [comment]
I'd say we should convert to toktok when it hits 0.1 (stable API release).
What do you say?
