### ISSUE TITLE
Consider switching to the toktok repo

### ISSUE THREAD

**Issue by e0ff** [pranomostro/ratox#9]
The toxcore repo under irungentoo's control is hardly ever updated. There is a fork now: https://github.com/toktok/toxcore that is making lots of progress.

**Comment by pranomostro** [comment]
I know about this fork.

However, the fork is not important for ratox, as it links against the local installed version of tox (and I have no plans of changing this).

**Comment by pranomostro** [comment]
Actually, after some consideration, I'll update to the toktok API.

**Comment by pranomostro** [comment]
Jep, updated. Thanks!
